apiVersion: v1
kind: Service
metadata:
  name: menu-service
spec:
  selector:
    app: menu
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30002 
  type: NodePort

